### ISSUE TITLE
Services, PVCs and ingresses

### ISSUE THREAD

**Issue by fntlnz** [gianarb/influxdb-operator#5]
We need to enable the creation of services, secrets, pvcs and ingress resources related to an influx, kapacitor or telegraf deployment.

When the services are available we can even populate deployment variables from the spec to allow interconnection of components via resource creation.

**Comment by gianarb** [comment]
We need to add secrets support too and ConfigMap for confgurations

**Comment by fntlnz** [comment]
Yea, thanks for pointing that out

**Comment by gianarb** [comment]
Closed. The boilerplate is merged and the scope of this issue is too big
